### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by Sahithya132002** [Sahithya132002/Final-Year-Project#8]
Hospital Management System Using MERN Stack

**Comment by ghost** [comment]
@Sahithya132002 , To have quality references, remove all reference if not available at [https://dblp.org/](https://dblp.org/)
and update the reference list. As you have given two thesis/Project report as reference, you can choose from: [https://oatd.org/](https://oatd.org/)
![image](https://github.com/user-attachments/assets/6f4c6676-f7cc-4fb8-9580-79eedee1a313)

**Comment by Sahithya132002** [comment]
Ok sir

**Comment by Sahithya132002** [comment]
The quality references are taken and they are available at https://dblp.org/ . I have updated references accordingly and added to Literature Survey folder in the repository.

**Comment by ghost** [comment]
Ok. Fine...
